=== bankaboy/IWPLab/LAB12 XML SCHEMA - 12 - 27.3.19/xml/xml programs/book.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bookdetails (book+)>
<!ELEMENT book (name+, author+, price+, publisher?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ATTLIST book bid CDATA #REQUIRED>
<!ENTITY ISBN "ISBN for book">

=== bankaboy/IWPLab/LAB12 XML SCHEMA - 12 - 27.3.19/xml/xml programs/ext_bookdetail.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookdetails SYSTEM "book.dtd">
<bookdetails>
    <book bid="101">
        <name>WS book</name>
        <author>Catherine</author>
        <price>120</price>
        <publisher>Apress</publisher>
    </book>
    <book bid="102">
        <name>WS java book</name>
        <author>Carolyn</author>
        <price>120</price>
        <publisher>&ISBN;Apress</publisher>
    </book>
</bookdetails>
