=== bankaboy/IWPLab/LAB12 XML SCHEMA - 12 - 27.3.19/xml/xml programs/purchaseorder.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="www.abc.com/purchase" xmlns:prd="www.abc.com/purchase">
<include schemaLocation="potype.xsd"/>
<element name="purchaseorder" type="prd:purord"/>
<complexType name="purord">
<sequence>
<element name="order" type="prd:ord"/>
</sequence>
<attribute name="prodid" type="prd:prstring"/>
<attribute name="orderid" type="prd:orstring" use="required"/>
</complexType>
<complexType name="ord">
<sequence>
<element name="DATE" type="date"/>
<element name="productname" type="string"/>
<element name="suppliername" type="string"/>
<element name="address" type="string"/>
<element name="quantity" type="positiveInteger"/>
<element name="priceperqty" type="positiveInteger"/>
</sequence>
</complexType>
</schema>

=== bankaboy/IWPLab/LAB12 XML SCHEMA - 12 - 27.3.19/xml/xml programs/purchase.xml
<?xml version="1.0" encoding="UTF-8"?>
<prd:purchaseorder xmlns:prd="www.abc.com/purchase" orderid="o001" prodid="p001" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="www.abc.com/purchase purchaseorder.xsd">
	<order>
		<DATE>2000-02-13</DATE>
		<productname>barbie doll</productname>
		<suppliername>barbie inc</suppliername>
		<address>barbie avenue</address>
		<quantity>123</quantity>
		<priceperqty>1000</priceperqty>
	</order>
</prd:purchaseorder>
